controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
      - robotiq_85_left_finger_joint
      - robotiq_85_right_finger_joint
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: zero
  - group: gripper
    pose: open