// Generated by gencpp from file position_tracker/GetPositionResponse.msg
// DO NOT EDIT!


#ifndef POSITION_TRACKER_MESSAGE_GETPOSITIONRESPONSE_H
#define POSITION_TRACKER_MESSAGE_GETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace position_tracker
{
template <class ContainerAllocator>
struct GetPositionResponse_
{
  typedef GetPositionResponse_<ContainerAllocator> Type;

  GetPositionResponse_()
    : x_position(0.0)
    , y_position(0.0)
    , z_position(0.0)  {
    }
  GetPositionResponse_(const ContainerAllocator& _alloc)
    : x_position(0.0)
    , y_position(0.0)
    , z_position(0.0)  {
  (void)_alloc;
    }



   typedef double _x_position_type;
  _x_position_type x_position;

   typedef double _y_position_type;
  _y_position_type y_position;

   typedef double _z_position_type;
  _z_position_type z_position;





  typedef boost::shared_ptr< ::position_tracker::GetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::position_tracker::GetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionResponse_

typedef ::position_tracker::GetPositionResponse_<std::allocator<void> > GetPositionResponse;

typedef boost::shared_ptr< ::position_tracker::GetPositionResponse > GetPositionResponsePtr;
typedef boost::shared_ptr< ::position_tracker::GetPositionResponse const> GetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::position_tracker::GetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::position_tracker::GetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::position_tracker::GetPositionResponse_<ContainerAllocator1> & lhs, const ::position_tracker::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x_position == rhs.x_position &&
    lhs.y_position == rhs.y_position &&
    lhs.z_position == rhs.z_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::position_tracker::GetPositionResponse_<ContainerAllocator1> & lhs, const ::position_tracker::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace position_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::position_tracker::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::position_tracker::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_tracker::GetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a65f5a0cdef54b2e1dbb78f7873209a";
  }

  static const char* value(const ::position_tracker::GetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a65f5a0cdef54b2ULL;
  static const uint64_t static_value2 = 0xe1dbb78f7873209aULL;
};

template<class ContainerAllocator>
struct DataType< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "position_tracker/GetPositionResponse";
  }

  static const char* value(const ::position_tracker::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_position\n"
"float64 y_position\n"
"float64 z_position\n"
;
  }

  static const char* value(const ::position_tracker::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_position);
      stream.next(m.y_position);
      stream.next(m.z_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::position_tracker::GetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::position_tracker::GetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "x_position: ";
    Printer<double>::stream(s, indent + "  ", v.x_position);
    s << indent << "y_position: ";
    Printer<double>::stream(s, indent + "  ", v.y_position);
    s << indent << "z_position: ";
    Printer<double>::stream(s, indent + "  ", v.z_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSITION_TRACKER_MESSAGE_GETPOSITIONRESPONSE_H
