// Generated by gencpp from file position_tracker/GetPosition.msg
// DO NOT EDIT!


#ifndef POSITION_TRACKER_MESSAGE_GETPOSITION_H
#define POSITION_TRACKER_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <position_tracker/GetPositionRequest.h>
#include <position_tracker/GetPositionResponse.h>


namespace position_tracker
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace position_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::position_tracker::GetPosition > {
  static const char* value()
  {
    return "4931ed2ee82bda66c8bc53fd24c21c60";
  }

  static const char* value(const ::position_tracker::GetPosition&) { return value(); }
};

template<>
struct DataType< ::position_tracker::GetPosition > {
  static const char* value()
  {
    return "position_tracker/GetPosition";
  }

  static const char* value(const ::position_tracker::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::position_tracker::GetPositionRequest> should match
// service_traits::MD5Sum< ::position_tracker::GetPosition >
template<>
struct MD5Sum< ::position_tracker::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::position_tracker::GetPosition >::value();
  }
  static const char* value(const ::position_tracker::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_tracker::GetPositionRequest> should match
// service_traits::DataType< ::position_tracker::GetPosition >
template<>
struct DataType< ::position_tracker::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::position_tracker::GetPosition >::value();
  }
  static const char* value(const ::position_tracker::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::position_tracker::GetPositionResponse> should match
// service_traits::MD5Sum< ::position_tracker::GetPosition >
template<>
struct MD5Sum< ::position_tracker::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::position_tracker::GetPosition >::value();
  }
  static const char* value(const ::position_tracker::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_tracker::GetPositionResponse> should match
// service_traits::DataType< ::position_tracker::GetPosition >
template<>
struct DataType< ::position_tracker::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::position_tracker::GetPosition >::value();
  }
  static const char* value(const ::position_tracker::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSITION_TRACKER_MESSAGE_GETPOSITION_H
